# Generated by Django 4.2.5 on 2023-12-03 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persons',
            old_name='passowrd',
            new_name='password',
        ),
    ]
